"""initial schema

Revision ID: 1ad8c0df45a9
Revises: 
Create Date: 2026-05-24 08:47:45.632862
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1ad8c0df45a9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('result', sa.Enum('success', 'failure', name='auditresult', native_enum=False), nullable=False),
    sa.Column('deploy_revision_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_target_type'), ['target_type'], unique=False)

    op.create_table('certificates',
    sa.Column('domains', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ok', 'pending', 'error', name='certificatestatus', native_enum=False), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_id'), ['id'], unique=False)

    op.create_table('deploy_revisions',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('initiated_by', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.Enum('auto', 'manual', name='deploymode', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', 'rolled_back', name='deploystatus', native_enum=False), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('health_result', sa.Enum('green', 'yellow', 'red', 'unknown', name='healthstatus', native_enum=False), nullable=False),
    sa.Column('rollback_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deploy_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deploy_revisions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deploy_revisions_number'), ['number'], unique=False)

    op.create_table('generated_configs',
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('traefik_dynamic', name='configkind', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apply_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_configs_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_configs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_configs_revision'), ['revision'], unique=False)

    op.create_table('health_checks',
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('green', 'yellow', 'red', 'unknown', name='healthstatus', native_enum=False), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_checks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_checks_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_checks_target_type'), ['target_type'], unique=False)

    op.create_table('secrets_metadata',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('secrets_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secrets_metadata_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_secrets_metadata_name'), ['name'], unique=True)

    op.create_table('sites',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('online', 'offline', 'degraded', 'disabled', 'archived', 'unknown', name='sitestatus', native_enum=False), nullable=False),
    sa.Column('wg_tunnel_subnet', sa.String(length=64), nullable=True),
    sa.Column('local_subnets', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('agent_version', sa.String(length=64), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gateway_peer_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sites_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('superadmin', 'operator', 'viewer', name='role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('nodes',
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('private_ip', sa.String(length=64), nullable=True),
    sa.Column('platform', sa.String(length=128), nullable=True),
    sa.Column('is_gateway', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('online', 'offline', 'unknown', name='nodestatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodes_id'), ['id'], unique=False)

    op.create_table('peers',
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=True),
    sa.Column('private_key_ref', sa.String(length=255), nullable=True),
    sa.Column('assigned_tunnel_ip', sa.String(length=64), nullable=True),
    sa.Column('allowed_ips', sa.JSON(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('persistent_keepalive', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.Enum('site_gateway', 'admin', name='peerrole', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('active', 'stale', 'disabled', 'unknown', name='peerstatus', native_enum=False), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_handshake', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transfer_rx', sa.BigInteger(), nullable=False),
    sa.Column('transfer_tx', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('peers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_peers_id'), ['id'], unique=False)

    op.create_table('services',
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('protocol_type', sa.Enum('http', 'https', 'tcp', 'udp', name='protocoltype', native_enum=False), nullable=False),
    sa.Column('backend_host', sa.String(length=255), nullable=False),
    sa.Column('backend_port', sa.Integer(), nullable=False),
    sa.Column('backend_scheme', sa.String(length=16), nullable=False),
    sa.Column('healthcheck_path', sa.String(length=255), nullable=True),
    sa.Column('healthcheck_expected_code', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('exposure_mode', sa.Enum('public', 'private', 'disabled', name='exposuremode', native_enum=False), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_slug'), ['slug'], unique=False)

    op.create_table('publications',
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('entrypoint_type', sa.Enum('web', 'tcp', 'udp', name='entrypointtype', native_enum=False), nullable=False),
    sa.Column('domain_or_sni', sa.String(length=255), nullable=True),
    sa.Column('path_prefix', sa.String(length=255), nullable=True),
    sa.Column('tls_enabled', sa.Boolean(), nullable=False),
    sa.Column('tls_mode', sa.Enum('off', 'letsencrypt', 'passthrough', 'custom', name='tlsmode', native_enum=False), nullable=False),
    sa.Column('published_port', sa.Integer(), nullable=True),
    sa.Column('public_enabled', sa.Boolean(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('middleware_profile', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publications_domain_or_sni'), ['domain_or_sni'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_id'), ['id'], unique=False)

    op.create_table('domains',
    sa.Column('fqdn', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('publication_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domains_fqdn'), ['fqdn'], unique=True)
        batch_op.create_index(batch_op.f('ix_domains_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domains_id'))
        batch_op.drop_index(batch_op.f('ix_domains_fqdn'))

    op.drop_table('domains')
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_id'))
        batch_op.drop_index(batch_op.f('ix_publications_domain_or_sni'))

    op.drop_table('publications')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_slug'))
        batch_op.drop_index(batch_op.f('ix_services_id'))

    op.drop_table('services')
    with op.batch_alter_table('peers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_peers_id'))

    op.drop_table('peers')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodes_id'))

    op.drop_table('nodes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_slug'))
        batch_op.drop_index(batch_op.f('ix_sites_id'))

    op.drop_table('sites')
    with op.batch_alter_table('secrets_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secrets_metadata_name'))
        batch_op.drop_index(batch_op.f('ix_secrets_metadata_id'))

    op.drop_table('secrets_metadata')
    with op.batch_alter_table('health_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_checks_target_type'))
        batch_op.drop_index(batch_op.f('ix_health_checks_target_id'))
        batch_op.drop_index(batch_op.f('ix_health_checks_id'))

    op.drop_table('health_checks')
    with op.batch_alter_table('generated_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_configs_revision'))
        batch_op.drop_index(batch_op.f('ix_generated_configs_id'))
        batch_op.drop_index(batch_op.f('ix_generated_configs_checksum'))

    op.drop_table('generated_configs')
    with op.batch_alter_table('deploy_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deploy_revisions_number'))
        batch_op.drop_index(batch_op.f('ix_deploy_revisions_id'))

    op.drop_table('deploy_revisions')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_id'))

    op.drop_table('certificates')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_target_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
